### ISSUE TITLE
KPI #4 — Institutional Users + Protocol Integrations

### ISSUE THREAD

**Issue by neodaoist** [valorem-labs-inc/valorem-subgraph#40]
**What:** An internal wiki (TBD) of Institutional Users + Protocol Integrations
**Why:** To support KPI reporting and OKR process

**Comment by neodaoist** [comment]
Not sure this one will be in subgraph ofc, but let's figure out how we might record and report on this number manually somehow

**Comment by 0xAlcibiades** [comment]
I say we just keep this in a notion page. Thoughts @neodaoist?

**Comment by neodaoist** [comment]
Awesome, thanks @0xAlcibiades for creating. I duped into Protocol Integrations and Market Makers to match our revised thinking from the Lean Canvas
